[package]
name = "bevyecs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
bevy_ecs = "0.13.2"
godot = { git = "https://github.com/godot-rust/gdext.git", branch = "master"}
lazy_static = "1.4.0"
