#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags


def add_sources(sources, dir, extension):
    for f in os.listdir(dir):
        if f.endswith("." + extension):
            sources.append(dir + "/" + f)

sources = []
add_sources(sources, ".", "cpp")
#add_sources(sources, "flecs", "c")

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["."])
env.Append(CPPPATH=["flecs_full/include"])

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../project/libperformance.{}.{}.framework/libperformance.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    env.Append(LINKFLAGS=['/NODEFAULTLIB:MSVCRT'])
    env.Append(LIBPATH=['flecs_full/out/Release'])
    env.Append(LIBS=['flecs'])
    library = env.SharedLibrary(
        "../project/libperformance{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
